# Generated by Django 4.0.3 on 2022-04-17 23:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import karuchka.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('body_color', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('body', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('number_of_doors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fuel', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('vehicle_type', models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED')], max_length=4)),
                ('gearing_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL'), ('SEMI_AUTOMATIC', 'SEMI_AUTOMATIC')], max_length=14)),
                ('gears', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('manufacturer_date', models.DateField(validators=[karuchka.common.validators.MinDateValidator(datetime.date(1920, 1, 1))])),
                ('vehicle_price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle_kilometers', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(upload_to='', validators=[karuchka.common.validators.MaxFileSizeInMbValidator(5)])),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
        ),
    ]
